modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-v2.1"

[[mods]]
modId="blueprintinternetconnectiondisabler"
version="${file.jarVersion}"
displayName="BlueprintInternetConnectionDisabler"
authors="Team Potato"
description='''

'''